# Generated by Django 2.2.12 on 2021-03-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='haulage_HL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='日期')),
                ('salesman', models.CharField(default='', max_length=30, verbose_name='业务员')),
                ('Purchase', models.CharField(default='', max_length=50, verbose_name='客户')),
                ('haulage_HL_people', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='运费')),
                ('remark_1', models.CharField(default='', max_length=50, verbose_name='备注')),
            ],
        ),
    ]
