# Generated by Django 2.2.12 on 2021-03-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts_receivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='出库日期')),
                ('FBillNo2', models.TextField(verbose_name='千方单据号')),
                ('word', models.TextField(verbose_name='产品长代码')),
                ('name_1', models.CharField(max_length=300, verbose_name='产品名称')),
                ('ITEM', models.CharField(max_length=300, verbose_name='规格型号')),
                ('unit', models.CharField(max_length=30, verbose_name='单位')),
                ('batch_number', models.TextField(verbose_name='批号')),
                ('number_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='销售数量')),
                ('price_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='销售单价')),
                ('money_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='销售金额')),
                ('Purchase', models.CharField(default='', max_length=50, verbose_name='购货单位')),
                ('administrative_office', models.CharField(default='', max_length=50, verbose_name='科室')),
                ('tax_rate_a', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='税率')),
                ('salesman', models.CharField(default='', max_length=30, verbose_name='业务员')),
                ('area_a', models.IntegerField(verbose_name='区域')),
                ('remark_a', models.CharField(default='', max_length=50, verbose_name='备注')),
                ('put_away', models.CharField(default='', max_length=50, verbose_name='收单情况')),
                ('fapiao_day', models.DateField(verbose_name='开票日期')),
                ('fapiao_number', models.IntegerField(verbose_name='发票号码')),
                ('put_money_date', models.DateField(verbose_name='回款日期')),
                ('put_money_number', models.TextField(verbose_name='回款银行编号')),
                ('put_money_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='回款金额')),
                ('type_1', models.CharField(default='', max_length=50, verbose_name='类型（试剂或设备）')),
            ],
        ),
    ]
