# Generated by Django 2.2.12 on 2021-03-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='make_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman', models.CharField(default='', max_length=30, verbose_name='业务员')),
                ('Purchase', models.CharField(default='', max_length=50, verbose_name='购货单位')),
                ('administrative_office', models.CharField(default='', max_length=50, verbose_name='科室')),
                ('day', models.DateField(verbose_name='出库日期')),
                ('FBillNo1', models.TextField(verbose_name='金蝶单据号')),
                ('FBillNo2', models.TextField(verbose_name='千方单据号')),
                ('VAR', models.CharField(max_length=50, verbose_name='品种')),
                ('word', models.TextField(verbose_name='产品长代码')),
                ('name_1', models.CharField(max_length=300, verbose_name='产品名称')),
                ('ITEM', models.CharField(max_length=300, verbose_name='规格型号')),
                ('unit', models.CharField(max_length=30, verbose_name='单位')),
                ('batch_number', models.TextField(verbose_name='批号')),
                ('number_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='销售数量')),
                ('price_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='销售单价')),
                ('money_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='销售金额')),
                ('haulage_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='托运费')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='单位成本')),
                ('Proportion_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='比例')),
                ('remark_1', models.CharField(default='', max_length=50, verbose_name='备注')),
                ('tax_rate_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='税率')),
                ('cost_A', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='成本A')),
                ('cost_B', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='成本B')),
                ('Margin_A', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='毛利A')),
                ('Margin_B', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='毛利B')),
                ('Tax_rate_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='企业所得税额')),
                ('Push_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='提成')),
            ],
        ),
    ]
